name: Deploy materialize-master

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'cloud_function/materialize-master/**'
      - '.github/workflows/deploy-materialize-master.yml'

permissions:
  contents: read
  id-token: write   # required for Workload Identity Federation

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT }}
  REGION: ${{ vars.GCP_REGION }}
  FUNCTION_NAME: materialize-master
  FUNCTION_DIR: cloud_function/materialize-master
  RUNTIME: python312
  BUCKET_NAME: ${{ vars.GCS_BUCKET }}
  # New tunables:
  TIMEOUT_SECONDS: "900"
  MEMORY: "2Gi"
  STRUCTURED_PREFIX: "structured"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.DEPLOYER_SA }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Verify source
        run: |
          ls -la "${FUNCTION_DIR}"
          test -f "${FUNCTION_DIR}/main.py"
          test -f "${FUNCTION_DIR}/requirements.txt"

      - name: Deploy Cloud Function (Gen2, HTTP)
        shell: bash
        run: |
          set -euo pipefail
          SA_FLAG=""
          # Optional: set vars.FUNCTION_SA to the runtime service account you want
          if [[ -n "${{ vars.FUNCTION_SA }}" ]]; then
            SA_FLAG="--service-account='${{ vars.FUNCTION_SA }}'"
          fi

          gcloud functions deploy "${FUNCTION_NAME}" \
            --gen2 \
            --region="${REGION}" \
            --runtime="${RUNTIME}" \
            --source="${FUNCTION_DIR}" \
            --entry-point="materialize_http" \
            --trigger-http \
            --timeout="${TIMEOUT_SECONDS}" \
            --memory="${MEMORY}" \
            ${SA_FLAG} \
            --set-env-vars="PROJECT_ID=${PROJECT_ID},GCS_BUCKET=${BUCKET_NAME},STRUCTURED_PREFIX=${STRUCTURED_PREFIX}"

      - name: Get Function URL
        id: cfurl
        run: |
          URL=$(gcloud functions describe "${FUNCTION_NAME}" --gen2 --region="${REGION}" --format='value(serviceConfig.uri)')
          echo "url=${URL}" >> "$GITHUB_OUTPUT"
          echo "Function URL: $URL"

      - name: Grant run.invoker to deployer SA (so Scheduler/CI can call it)
        run: |
          gcloud functions add-invoker-policy-binding "${FUNCTION_NAME}" \
            --gen2 --region="${REGION}" \
            --member="serviceAccount:${{ vars.DEPLOYER_SA }}"

      - name: Ensure Scheduler API enabled (best-effort)
        run: |
          gcloud services enable cloudscheduler.googleapis.com || echo "Assuming Scheduler API already enabled."

      - name: Create/Update Cloud Scheduler job (:10 each hour)
        shell: bash
        run: |
          set -euo pipefail
          gcloud config set project "${PROJECT_ID}" >/dev/null
          JOB_NAME="materialize-master-hourly"
          FUNCTION_URL="${{ steps.cfurl.outputs.url }}"
          test -n "${FUNCTION_URL}"

          if gcloud scheduler jobs describe "$JOB_NAME" --location="${REGION}" >/dev/null 2>&1; then
            gcloud scheduler jobs update http "$JOB_NAME" \
              --location="${REGION}" \
              --schedule="10 * * * *" \
              --time-zone="America/New_York" \
              --uri="${FUNCTION_URL}" \
              --http-method=POST \
              --headers="Content-Type=application/json" \
              --body="{}" \
              --attempt-deadline="${TIMEOUT_SECONDS}s" \
              --oidc-service-account-email="${{ vars.DEPLOYER_SA }}"
          else
            gcloud scheduler jobs create http "$JOB_NAME" \
              --location="${REGION}" \
              --schedule="10 * * * *" \
              --time-zone="America/New_York" \
              --uri="${FUNCTION_URL}" \
              --http-method=POST \
              --headers="Content-Type=application/json" \
              --body="{}" \
              --attempt-deadline="${TIMEOUT_SECONDS}s" \
              --oidc-service-account-email="${{ vars.DEPLOYER_SA }}"
          fi

      - name: Smoke invoke (returns quickly if your handler logs and exits)
        shell: bash
        run: |
          set -euo pipefail
          URL="${{ steps.cfurl.outputs.url }}"
          TOKEN="$(gcloud auth print-identity-token)"
          echo "POST $URL"
          curl -i -sS -X POST "$URL" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{}' || true  # don't fail the workflow if your run takes longer than GitHub's curl wait
