name: Deploy extractor-per-listing (Gen2)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'functions/extractor-per-listing/**'
      - '.github/workflows/deploy-extractor.yml'

permissions:
  contents: read
  id-token: write   # REQUIRED for WIF/OIDC

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}         # <-- set in repo secrets
  REGION: ${{ secrets.GCP_REGION }}              # <-- set in repo secrets (e.g., us-central1)
  FUNCTION_NAME: extractor-per-listing
  FUNCTION_DIR: functions/extractor-per-listing
  RUNTIME: python312
  BUCKET_NAME: ${{ secrets.GCS_BUCKET }}         # <-- set in repo secrets

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Authenticate via Workload Identity Federation (recommended, no JSON keys)
      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}   # e.g. projects/123.../locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}                   # e.g. gha-deployer@PROJECT.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Verify source
        run: |
          ls -la "${FUNCTION_DIR}"
          test -f "${FUNCTION_DIR}/main.py"
          test -f "${FUNCTION_DIR}/requirements.txt"

      - name: Deploy Cloud Function (Gen2, HTTP, authenticated)
        run: |
          gcloud functions deploy "${FUNCTION_NAME}" \
            --gen2 \
            --region="${REGION}" \
            --runtime="${RUNTIME}" \
            --source="${FUNCTION_DIR}" \
            --entry-point="extract_http" \
            --trigger-http \
            --set-env-vars="GCS_BUCKET=${BUCKET_NAME},SCRAPES_PREFIX=scrapes,STRUCTURED_PREFIX=structured"

      - name: Get Function URL
        id: cfurl
        run: |
          URL=$(gcloud functions describe "${FUNCTION_NAME}" --gen2 --region="${REGION}" --format='value(serviceConfig.uri)')
          echo "url=${URL}" >> "$GITHUB_OUTPUT"

      # Optional: grant invoker to your deployer SA (so Scheduler can use it too)
      - name: Grant run.invoker to deployer SA
        run: |
          gcloud functions add-invoker-policy-binding "${FUNCTION_NAME}" \
            --gen2 --region="${REGION}" \
            --member="serviceAccount:${{ secrets.SERVICE_ACCOUNT_EMAIL }}"

      # Optional: create/update Scheduler job at :05
      - name: Create/Update Cloud Scheduler job (:05)
        run: |
          JOB_NAME="extract-per-listing-hourly"
          FUNCTION_URL="${{ steps.cfurl.outputs.url }}"
          if gcloud scheduler jobs describe "$JOB_NAME" --location="${REGION}" >/dev/null 2>&1; then
            gcloud scheduler jobs update http "$JOB_NAME" \
              --location="${REGION}" \
              --schedule="5 * * * *" \
              --time-zone="America/New_York" \
              --uri="${FUNCTION_URL}" \
              --http-method=POST \
              --message-body='{"overwrite": true, "max_files": 0}' \
              --oidc-service-account-email="${{ secrets.SERVICE_ACCOUNT_EMAIL }}"
          else
            gcloud scheduler jobs create http "$JOB_NAME" \
              --location="${REGION}" \
              --schedule="5 * * * *" \
              --time-zone="America/New_York" \
              --uri="${FUNCTION_URL}" \
              --http-method=POST \
              --message-body='{"overwrite": true, "max_files": 0}' \
              --oidc-service-account-email="${{ secrets.SERVICE_ACCOUNT_EMAIL }}"
          fi
